// copiloto-conversa (v58) — verify_jwt=false. Base v57. 4 INTELIGENCIAS FUNCIONAIS (ferramentas fixas, a prova de erro): preco_produto (preco da TABELA do cliente = TGFEXC na CODTAB dele), credito_cliente (limite/bloqueio/vencido/pode comprar), estoque_produto (TGFEST disp = estoque-reservado), entrega_cliente (VW_PEDIDOS_ENTREGAR + AD_TSIAGENENT). Preco: rep ve; cliente final nao. v57: todas as skills carregadas. CEREBRO GERAL: Sonnet 5 responde TUDO (fim do Haiku no caminho principal, que era inconsistente). REGRA DE OURO: sempre consultar Sankhya AO VIVO p/ rep E cliente, todos os fatos. cobranca_cliente agora ao vivo (TGFFIN); buscar_cliente com fallback ao vivo (TGFPAR). v55 mantido: pedidos_pendentes, SANKHYA_HINT corrigido, HOJE, rep=1 conversa/persona.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SRK = Deno.env.get("SRV_JWT") || Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, content-type, apikey, x-copiloto-secret", "Access-Control-Allow-Methods": "POST, OPTIONS" };
const j = (o: unknown, s = 200) => new Response(JSON.stringify(o), { status: s, headers: { ...cors, "Content-Type": "application/json" } });
const MODELO = "claude-haiku-4-5-20251001";
const MODELO_HARD = "claude-sonnet-5";
function ehComplexo(t: any){ const s = norm(t); return /(plano completo|plano de a|planilha|relatorio completo|todos os clientes|cliente a cliente|lista completa|analise completa|detalhad|cruz|comparar|estrateg|passo a passo|montar|construir|elaborar|prioriz|vender mais|o que posso fazer|o que eu posso|o que fazer|reativ)/.test(s); }
const GHL = (Deno.env.get("GHL_TOKEN") || "").trim();
const OAI = (Deno.env.get("OPENAI_API_KEY") || "").trim();
const LOC = "rZ8y7lzqV7fzxsartaX2";
const digits = (s: any) => String(s || "").replace(/\D/g, "");
const d10 = (s: any) => digits(s).slice(-10);
const fk8 = (s: any) => { let d = digits(s).replace(/^0+/, "").replace(/^55/, ""); if (d.length > 8) d = d.slice(-8); return d; };
const norm = (s: any) => String(s || "").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").trim();
const prim = (s: any) => (String(s || "").trim().split(/\s+/)[0] || String(s || ""));
function hojeBRT(): string { const d = new Date(Date.now() - 3 * 3600 * 1000); const p = (n: number) => String(n).padStart(2, "0"); return p(d.getUTCDate()) + "/" + p(d.getUTCMonth() + 1) + "/" + d.getUTCFullYear(); }
let SK: any = null;
async function skLogin() { const base = (Deno.env.get("SANKHYA_URL") || "").replace(/\/$/, ""); const u = Deno.env.get("SANKHYA_USER"); const p = Deno.env.get("SANKHYA_PASS"); if (!base || !u || !p) throw new Error("sem credenciais sankhya"); const r = await fetch(`${base}/mge/service.sbr?serviceName=MobileLoginSP.login&outputType=json`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ serviceName: "MobileLoginSP.login", requestBody: { NOMUSU: { $: u }, INTERNO: { $: p }, KEEPCONNECTED: { $: "true" } } }) }); const d = JSON.parse(new TextDecoder("iso-8859-1").decode(await r.arrayBuffer())); const s = d?.responseBody?.jsessionid?.$ ?? d?.responseBody?.jsessionid ?? ""; if (!s) throw new Error("login sankhya falhou"); return { base, jsession: String(s), cookie: `JSESSIONID=${s}` }; }
async function skExec(sql: string): Promise<{ fields: string[]; rows: any[][]; erro: string | null }> {
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      if (!SK) SK = await skLogin();
      const url = `${SK.base}/mge/service.sbr?serviceName=DbExplorerSP.executeQuery&outputType=json&mgeSession=${encodeURIComponent(SK.jsession)}`;
      const r = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json", Cookie: SK.cookie }, body: JSON.stringify({ serviceName: "DbExplorerSP.executeQuery", requestBody: { sql } }) });
      const d = JSON.parse(new TextDecoder("iso-8859-1").decode(await r.arrayBuffer()));
      const ok = String(d?.status ?? "1") === "1";
      if (!ok) { const msg = String(d?.statusMessage || "erro sankhya"); if (attempt === 0 && /sess|login|autoriz|expir/i.test(msg)) { SK = null; continue; } return { fields: [], rows: [], erro: msg.slice(0, 200) }; }
      const fm = d?.responseBody?.fieldsMetadata || d?.responseBody?.fields || []; const fields = (fm as any[]).map((f) => f?.name || f?.descricao || f?.field || "");
      const rows = (d?.responseBody?.rows || []) as any[][];
      return { fields, rows, erro: null };
    } catch (e) { if (attempt === 0) { SK = null; continue; } return { fields: [], rows: [], erro: String(e).slice(0, 200) }; }
  }
  return { fields: [], rows: [], erro: "falha sankhya" };
}
const SK_BLOQ_TAB = /(\b|\.)(TFP\w*|TRH\w*|TSIUSU\w*|TPR\w*|TCB\w*|TGFFIN|TGFCX\w*|TGFCTB\w*|TCTB\w*|TSICUS\w*)(\b)/i;
const SK_BLOQ_KW = /(salario|sal[a]?rios|folha de pagamento|holerite|contracheque|contra-cheque|apontament|ordem de produ|conta[s]? a pagar|contas a pagar|fluxo de caixa|movimenta\w* financeir|tesouraria)/i;
function checarSql(sql: any): { ok: boolean; sql?: string; motivo?: string } {
  let s = String(sql || "").trim().replace(/;+\s*$/, "");
  if (!/^select\b/i.test(s)) return { ok: false, motivo: "apenas UM SELECT de leitura e permitido" };
  if (/\b(insert|update|delete|drop|alter|truncate|merge|create|grant|revoke|begin|declare|execute|exec|call)\b/i.test(s)) return { ok: false, motivo: "comando de escrita/alteracao bloqueado (somente leitura)" };
  if (SK_BLOQ_TAB.test(s) || SK_BLOQ_KW.test(s)) return { ok: false, motivo: "RESTRITO: sem acesso a RH/folha/salarios, dados de funcionarios, producao/apontamentos, nem movimentacao financeira de pagamentos/tesouraria. Para BOLETO/titulos a receber do cliente use a ferramenta boleto_cliente. Consulte apenas dados COMERCIAIS." };
  if (!/rownum/i.test(s) && !/fetch\s+first/i.test(s)) s = `SELECT * FROM (${s}) WHERE ROWNUM <= 60`;
  return { ok: true, sql: s };
}
function foraHorarioComercial(): boolean { const brt = new Date(Date.now() - 3 * 3600 * 1000); const dow = brt.getUTCDay(); const h = brt.getUTCHours(); if (dow === 0) return true; if (dow === 6) return h < 8 || h >= 13; return h < 8 || h >= 18; }
function pickText(b: any): string {
  const cand = [b?.texto, b?.message, b?.body, b?.messageBody, b?.sms, b?.text, b?.content, b?.customData?.Texto, b?.customData?.texto];
  for (const c of cand) { if (typeof c === "string") { const t = c.trim(); if (t && t !== "[object Object]") return t; } else if (c && typeof c === "object") { const inner = c.body || c.message || c.text || c.content || c.sms || c.payload; if (typeof inner === "string" && inner.trim()) return inner.trim(); } }
  return "";
}
function parseInstance(t: string): { inst: string | null; clean: string } { if (!t) return { inst: null, clean: t }; const m = t.match(/Instance Source:\s*([^\n]+)\s*$/i); const inst = m ? m[1].trim() : null; const clean = t.replace(/\n*\s*Instance Source:\s*[^\n]+\s*$/i, "").trim(); return { inst, clean }; }
function urlAnexo(a: any): string { if (!a) return ""; if (typeof a === "string") { const m = a.match(/https?:\/\/[^\s,"'\]]+/); return m ? m[0] : ""; } if (Array.isArray(a)) { for (const x of a) { const u = typeof x === "string" ? x : (x?.url || x?.href || ""); if (u && /^https?:/.test(String(u))) return String(u); } } if (typeof a === "object") { const u = a.url || a.href || ""; if (u) return String(u); } return ""; }
function gv(b: any, ...keys: string[]): string { for (const k of keys) { const v = b?.[k]; if (v != null && String(v).trim() && String(v).trim().toLowerCase() !== "null") return String(v).trim(); } return ""; }
function dossieDoPayload(b: any): { txt: string; nome: string; empresa: string; ramo: string; codparc: string } {
  const empresa = gv(b, "company_name", "Razão Social", "Nome da Empresa"); const nome = gv(b, "first_name", "full_name"); const codparc = gv(b, "Codigo Parceiro"); const ramo = gv(b, "Ramo Atuacao", "Ramo Atuação"); const canal = gv(b, "Canal"); const situ = gv(b, "Situação Recompra"); const dias = gv(b, "Dias sem compra"); const tit = gv(b, "Titulos Vencidos", "Títulos Vencidos"); const clube = gv(b, "Saldo Clube", "clube_saldo_pedir"); const ai = gv(b, "Informações para ai", "Informações para AI", "Informacoes para ai", "informaes_para_ai");
  const ident: string[] = []; if (empresa) ident.push("empresa: " + empresa); if (nome) ident.push("contato: " + nome); if (codparc) ident.push("codparc " + codparc); if (ramo) ident.push("ramo " + ramo); if (canal) ident.push("canal " + canal); if (situ) ident.push("situacao " + situ); if (dias) ident.push(dias + " dias sem comprar"); if (tit && Number(String(tit).replace(/[^0-9.]/g, "")) > 0) ident.push("TITULOS VENCIDOS R$ " + tit); if (clube && Number(String(clube).replace(/[^0-9.]/g, "")) > 0) ident.push("tem saldo de Clube");
  let txt = ""; if (ident.length) txt += "DADOS REAIS DESTE CONTATO (do CRM — JA SABE, NAO pergunte): " + ident.join("; ") + "."; if (ai && ai.length > 20) txt += (txt ? "\n" : "") + "DOSSIE: " + ai.slice(0, 1200); return { txt, nome, empresa, ramo, codparc };
}
async function memoria360(sb: any, contactId: string | null, codparc: number | null): Promise<string> {
  const blocos: string[] = [];
  if (contactId && GHL) {
    try {
      const s = await fetch(`https://services.leadconnectorhq.com/conversations/search?locationId=${LOC}&contactId=${contactId}&limit=10`, { headers: { Authorization: "Bearer " + GHL, Version: "2021-04-15", Accept: "application/json" } });
      const sd = await s.json().catch(() => ({})); const convs = sd?.conversations || [];
      const linhas: string[] = [];
      for (const cv of (Array.isArray(convs) ? convs : []).slice(0, 4)) {
        const m = await fetch(`https://services.leadconnectorhq.com/conversations/${cv.id}/messages?limit=12`, { headers: { Authorization: "Bearer " + GHL, Version: "2021-04-15", Accept: "application/json" } });
        const md = await m.json().catch(() => ({})); const arr = md?.messages?.messages || md?.messages || [];
        for (const x of (Array.isArray(arr) ? arr : [])) { const body = String(x?.body || "").replace(/\n+/g, " ").replace(/Instance Source:.*/i, "").replace(/#contact_instance:\S+/i, "").trim(); if (!body || norm(body) === "ptt") continue; linhas.push((x.direction === "inbound" ? "Contato: " : "Nitron: ") + body.slice(0, 160)); }
      }
      if (linhas.length) blocos.push("CONVERSAS ANTERIORES NO WHATSAPP (qualquer assistente/canal - vendas, cobranca, logistica):\n- " + linhas.slice(-20).join("\n- "));
    } catch (_e) { /* */ }
  }
  if (codparc) { try { const { data } = await sb.from("voz_ligacao").select("interesse, proximo_passo, observacao").eq("codparc", codparc).order("criado", { ascending: false }).limit(3); if (data && data.length) blocos.push("LIGACOES ANTERIORES (voz):\n- " + (data as any[]).map((l) => `(${l.interesse || "-"}) ${l.observacao || l.proximo_passo || ""}`.trim()).join("\n- ")); } catch (_e) { /* */ } }
  if (contactId) { try { const { data } = await sb.from("transcricoes").select("texto, tipo").eq("contact_id", contactId).not("texto", "is", null).order("criado_em", { ascending: false }).limit(4); if (data && data.length) blocos.push("TRANSCRICOES DE AUDIO/VOZ ANTERIORES:\n- " + (data as any[]).reverse().map((t) => String(t.texto).replace(/\s+/g, " ").slice(0, 250)).join("\n- ")); } catch (_e) { /* */ } }
  return blocos.join("\n\n");
}
async function transcrever(url: string): Promise<string> {
  try { const a = await fetch(url); if (!a.ok) return ""; const buf = new Uint8Array(await a.arrayBuffer()); const base = url.split("?")[0]; const ext = (base.match(/\.(mp3|mpeg|ogg|oga|opus|m4a|mp4|wav|amr|aac|webm|flac)$/i)?.[1] || "mp3").toLowerCase(); const mime = ext === "mp3" || ext === "mpeg" ? "audio/mpeg" : ext === "m4a" || ext === "mp4" ? "audio/mp4" : ext === "wav" ? "audio/wav" : ext === "webm" ? "audio/webm" : ext === "amr" ? "audio/amr" : ext === "aac" ? "audio/aac" : ext === "flac" ? "audio/flac" : "audio/ogg"; const form = new FormData(); form.append("file", new Blob([buf], { type: mime }), "audio." + (ext === "mpeg" ? "mp3" : ext)); form.append("model", "gpt-4o-mini-transcribe"); form.append("language", "pt"); form.append("response_format", "json"); const r = await fetch("https://api.openai.com/v1/audio/transcriptions", { method: "POST", headers: { Authorization: "Bearer " + OAI }, body: form }); if (!r.ok) return ""; const d = await r.json().catch(() => ({})); return String(d.text || "").trim(); } catch { return ""; }
}
async function verImagem(url: string): Promise<string> {
  const key = Deno.env.get("ANTHROPIC_API_KEY"); if (!key || !url) return ""; try { const r = await fetch("https://api.anthropic.com/v1/messages", { method: "POST", headers: { "x-api-key": key, "anthropic-version": "2023-06-01", "content-type": "application/json" }, body: JSON.stringify({ model: MODELO, max_tokens: 400, messages: [{ role: "user", content: [{ type: "image", source: { type: "url", url } }, { type: "text", text: "Descreva em portugues, objetivo, o que ha nesta imagem util p/ atendimento comercial Nitron: PRODUTO (qual)? BOLETO/nota (valor/venc)? PRINT de tabela/pedido? FOTO de loja? 2-3 linhas." }] }] }) }); if (!r.ok) return ""; const d = await r.json().catch(() => ({})); const blocks = d?.content || []; return blocks.filter((x: any) => x.type === "text").map((x: any) => x.text).join(" ").trim().slice(0, 700); } catch { return ""; }
}
function detectarTema(t: string): string { const s = norm(t); if (/(boleto|2a via|segunda via|linha digitavel|pagament|pagar|titulo|vencid|pix|divida|debito|duplicata|parcel|inadimpl|nota atrasada|cobran|acordo)/.test(s)) return "cobranca"; if (/(entrega|entregar|agendar|agendament|carga|transportador|redespacho|coleta|reagend|chegou|nao chegou|prazo de entrega|faltou|avaria|recebi a mercadoria)/.test(s)) return "logistica"; if (/(minha meta|minha carteira|meus clientes|quem visito|quem ligo|roteiro|positiv|ritmo|bater a meta|minhas vendas do mes|clientes parados|clientes meus|pendentes de liberar|a liberar|pendente de entrega|relacao de todos)/.test(s)) return "representante"; return "vendas"; }
async function catalogoTxt(sb: any, cfg: Record<string, string>): Promise<string> {
  try { const { data } = await sb.from("linha_produto").select("linha, qtd_prod_ativos, relevancia, activa, linha_negocio").eq("activa", true); const nome = (l: string) => String(l || "").replace(/^Linha\s+/i, ""); const plast = (data || []).filter((r: any) => String(r.linha_negocio) !== "MADEIRA" && Number(r.qtd_prod_ativos) > 0); const carro = plast.filter((r: any) => r.relevancia >= 5).map((r: any) => nome(r.linha)); const fortes = plast.filter((r: any) => r.relevancia === 4 || r.relevancia === 3).map((r: any) => nome(r.linha)); let s = "CATALOGO (Nitron): utilidades pra casa, PRINCIPALMENTE PLASTICO. "; if (carro.length) s += "Carro-chefe: " + carro.join(", ") + ". "; if (fortes.length) s += "Fortes: " + fortes.join(", ") + ". "; s += "Madeira: TECA (tabuas) e MOB (moveis pinus). PRECO: para o REPRESENTANTE/interno use a ferramenta preco_produto (traz o preco da TABELA DO CLIENTE, atacado); ao CLIENTE final NAO cite preco de produto (site=varejo), direcione ao vendedor. "; const cat = cfg.catalogo_url || ""; const site = cfg.site_url || ""; if (cat) s += "CATALOGO PDF: " + cat + " . "; if (site) s += "SITE: " + site + " . "; return s; } catch (_e) { return ""; }
}
const REGRAS = `\n\nESTILO (HUMANO, nao IA): frases curtas, naturais. EVITE negrito e listas. Sem emoji em toda msg.\nRESPONDA PRIMEIRO E DIRETO exatamente o que perguntaram (o dado objetivo) e SO DEPOIS complemente. Nao enrole antes da resposta.\nSANKHYA SEMPRE AO VIVO (REGRA DE OURO — vale IGUAL p/ REPRESENTANTE E p/ CLIENTE): antes de responder QUALQUER fato concreto (pedido, nota, faturamento, saldo, boleto/titulo, prazo, status de entrega/agendamento, cadastro, situacao do cliente, disponibilidade) voce TEM que consultar o Sankhya ao vivo pelas ferramentas (pedidos_pendentes, pedido_cliente, boleto_cliente, cobranca_cliente, saldos_cliente, buscar_cliente, minha_carteira, consultar_sankhya). NUNCA responda de cabeca, de memoria, nem de um resumo/espelho — confirme SEMPRE no sistema, mesmo que ache que ja sabe. So diga 'vou confirmar e retorno' se a ferramenta REALMENTE nao trouxer nada. NUNCA invente preco, saldo, prazo, pedido, status.\nACOES QUE PRECISAM MEXER NO SANKHYA (faturar/liberar/corrigir/cadastrar/devolver/liberar credito): voce NAO grava no Sankhya - abra uma tarefa com a ferramenta abrir_tarefa e passe o PROTOCOLO pro rep. Consulta voce resolve; acao voce encaminha.\nRESTRICOES ABSOLUTAS (nunca contornar): voce NAO acessa nem informa salarios, dados de funcionarios/RH, apontamentos/ordens de producao, nem movimentacao financeira de pagamentos/contas a pagar/tesouraria.\nBOLETO/DADOS FINANCEIROS (para CLIENTE): so envie boleto/2a via/titulos se o contato JA estiver vinculado ao cadastro (codparc) OU o cliente CONFIRMAR o CNPJ. (Rep/gestor interno consultando a carteira nao precisa disso.)\nVENCIDO x A VENCER: so 'vencido' se a data JA passou; futuro = a_vencer = normal.\nVINCULO BOLETO->PEDIDO->NOTA->ENTREGA: todo boleto traz o NUNOTA; derive pedido/nota/faturamento/entrega via consultar_sankhya (nao peca numero que da pra derivar).\nEMPRESA: aqui e a NITRON. Nunca cite 'Hyak', 'Teak' ou 'Roga' ao cliente/rep.\nMEMORIA: NAO pergunte o que ja sabe.`;
const SYS_PESSOA = (nome: string) => `Voce e a ${nome}, do time comercial da Nitronplast (Nitron), por WhatsApp. Calorosa e natural, pessoa de verdade da equipe. NAO diga que e IA/bot; voce e a ${nome}.` + REGRAS;
const SYS_NEUTRO = () => `Voce e o time comercial da Nitronplast (Nitron), por WhatsApp. Nao invente nome proprio. Calorosa e natural. NAO diga que e IA/bot.` + REGRAS;
const SYS_INFORMATIVO = `\n\nMODO INFORMATIVO: responda o essencial e encaminhe ao comercial para fechar.`;
const SANKHYA_HINT = "TABELAS COMERCIAIS PERMITIDAS (Oracle, use ROWNUM p/ limitar, TO_CHAR p/ datas): TGFPAR (parceiros/clientes: CODPARC, RAZAOSOCIAL, NOMEPARC, CGC_CPF, ATIVO, CODVEND, CODTAB, CODCID, CODPARCMATRIZ, LIMCRED, BLOQUEAR). TGFCAB (pedidos/notas: NUNOTA, CODPARC, CODVEND, DTNEG, DTFATUR, TIPMOV[P=pedido / V=nota faturada / D=devolucao], STATUSNOTA[A=Atendimento(em aberto, NAO liberado) / L=Liberada / P=Pendente], PENDENTE[S=ainda tem saldo a faturar / N=ja faturado/encerrado], VLRNOTA, AD_STATUFORCA[etapa da forca de vendas: ELAB_COMERC/ELAB_CLIENTE=em elaboracao, AGUARD_REV/AGUARD_APR/AGUARD_CONF=aguardando liberacao, APROVADO, AGUARD_FAT=aguardando faturamento], CODTIPVENDA, ORDEMCARGA, NUMNOTA, STATUSNFE). CICLO DO PEDIDO: pedido A LIBERAR = TIPMOV 'P' e STATUSNOTA 'A' e PENDENTE 'S'; pedido A FATURAR (liberado, aguardando nota) = TIPMOV 'P' e STATUSNOTA 'L' e PENDENTE 'S'; FATURADO = TIPMOV 'V' (a nota). Para pedidos/faturamento DE UM REPRESENTANTE, SEMPRE filtre CAB.CODVEND=<codvend do rep> E DTNEG dos ULTIMOS MESES (ADD_MONTHS(SYSDATE,-6)) — NUNCA traga anos anteriores. Mas o certo p/ isso e usar a ferramenta pedidos_pendentes (ja vem pronta). TGFITE (itens). TGFPRO (produtos). TGFEST (estoque). TGFTPV (prazo). AD_TSIAGENENT (agendamento por NUNOTA). VW_PEDIDOS_ENTREGAR (fila de expedicao). SEMPRE traga o NOME do cliente (JOIN TGFPAR NOMEPARC/RAZAOSOCIAL) e datas com TO_CHAR - quem le nao conhece codparc/NUNOTA. Exclua intercompany CODPARC NOT IN (1,68200). VIEWS: VW_PARC_INADIMPLENCIA, VW_PEDIDOS_FATURAR. PROIBIDO: RH (TFP*), TSIUSU, producao (TPR*), tesouraria (TCB*, TGFFIN - boleto usa boleto_cliente).";
const TOOLS = [
  { name: "buscar_cliente", description: "Perfil rapido de cliente (espelho) por CODIGO(codparc), CNPJ ou nome: razao, ultimo faturamento (dias), situacao, ticket, canal, ramo, mix, saldo, titulos, clube.", input_schema: { type: "object", properties: { termo: { type: "string" } }, required: ["termo"] } },
  { name: "pedido_cliente", description: "AO VIVO no Sankhya: ultimos pedidos/notas de um cliente (codparc) com DATA, tipo, status, valor e PRAZO DE PAGAMENTO. Use p/ ultimo pedido/prazo/o que comprou/ultima negociacao.", input_schema: { type: "object", properties: { codparc: { type: "integer" } }, required: ["codparc"] } },
  { name: "boleto_cliente", description: "AO VIVO: boletos/2a via/titulos a receber em aberto do cliente (por codparc) - valor, vencimento, SITUACAO (vencido/a_vencer), NUNOTA, linha digitavel, banco. So com o cliente identificado ao codparc.", input_schema: { type: "object", properties: { codparc: { type: "integer" } }, required: ["codparc"] } },
  { name: "consultar_conhecimento", description: "Base de conhecimento sobre COMO Sankhya/GHL/integracao/campanhas funcionam (preco, boletos, agendamento, pipelines, clube, voucher, faturamento, ciclo do pedido, triagem, MAPA DE VINCULOS). Passe um assunto.", input_schema: { type: "object", properties: { termo: { type: "string" } }, required: ["termo"] } },
  { name: "consultar_sankhya", description: "AO VIVO: roda UM SELECT de LEITURA em tabelas COMERCIAIS do Sankhya. SEMPRE traga o nome do cliente e datas legiveis. " + SANKHYA_HINT, input_schema: { type: "object", properties: { sql: { type: "string", description: "um unico SELECT Oracle, so dados comerciais" } }, required: ["sql"] } },
  { name: "produtos", description: "Produtos do site por categoria/nome/ramo. Retorna nome e LINK (foto). Sem preco.", input_schema: { type: "object", properties: { termo: { type: "string" } }, required: ["termo"] } },
  { name: "saldos_cliente", description: "Saldos (sobra de pedidos) do cliente pelo codparc.", input_schema: { type: "object", properties: { codparc: { type: "integer" } }, required: ["codparc"] } },
  { name: "cobranca_cliente", description: "Cobranca (titulos a RECEBER) do cliente pelo codparc: vencido, maior atraso, n titulos.", input_schema: { type: "object", properties: { codparc: { type: "integer" } }, required: ["codparc"] } },
  { name: "minha_carteira", description: "Carteira do representante: resumo (total, parados, inadimplentes, clube) E a LISTA COMPLETA de todos os clientes dele (codparc, nome, dias sem compra, faturamento 12m, inadimplencia, clube, cidade/uf). Use p/ 'minha carteira', 'meus clientes', 'relacao de todos', 'quais parados', 'quais com codigo'.", input_schema: { type: "object", properties: {}, required: [] } },
  { name: "pedidos_pendentes", description: "AO VIVO e JA FILTRADO na carteira do rep (codvend dele): pedidos A FATURAR (liberados, aguardando emissao da nota), A LIBERAR (aguardando revisao/aprovacao interna), EM ELABORACAO (rep/cliente ainda montando) e FATURADOS no mes atual — cada um com NOME do cliente, data, valor e a ETAPA onde esta a pendencia. USE SEMPRE que o rep perguntar 'o que tenho a faturar', 'a liberar', 'pendente', 'faturei esse mes', 'pedidos parados pra faturar'. NAO escreva SQL pra isso e NAO use consultar_sankhya: use esta ferramenta. So traz clientes DELE, dos ultimos meses, sem intercompany — nunca pedido de anos atras.", input_schema: { type: "object", properties: {}, required: [] } },
  { name: "preco_produto", description: "PRECO EXATO da TABELA DO CLIENTE: dado o codparc do cliente e um produto (nome ou codprod), devolve o preco de atacado que ESSE cliente paga (TGFEXC na tabela CODTAB dele) + codigo do produto. A inteligencia JA sabe qual tabela aplica a cada cliente (e a CODTAB dele). Use quando cliente/rep perguntar preco de um item. NUNCA invente nem use preco de site/varejo.", input_schema: { type: "object", properties: { codparc: { type: "integer" }, produto: { type: "string" } }, required: ["codparc", "produto"] } },
  { name: "credito_cliente", description: "CREDITO E BLOQUEIO do cliente (codparc), AO VIVO: limite de credito, saldo em aberto, valor vencido, credito disponivel, se esta BLOQUEADO (e o motivo) e se PODE COMPRAR agora. Use ANTES de fechar/empurrar venda e quando perguntarem de limite/bloqueio. Regra: nao vende a quem tem titulo vencido.", input_schema: { type: "object", properties: { codparc: { type: "integer" } }, required: ["codparc"] } },
  { name: "estoque_produto", description: "DISPONIBILIDADE/ESTOQUE de um produto (nome ou codprod), AO VIVO (estoque proprio menos reservado). Use ANTES de prometer entrega/quantidade. Regra: nao prometer sem stock confirmado.", input_schema: { type: "object", properties: { produto: { type: "string" } }, required: ["produto"] } },
  { name: "entrega_cliente", description: "STATUS e AGENDAMENTO de ENTREGA, AO VIVO (VW_PEDIDOS_ENTREGAR + AD_TSIAGENENT): por codparc (entregas pendentes do cliente) ou por nunota (um pedido) - status na expedicao, previsao de entrega, transportadora, se precisa agendar e a data agendada. Use p/ 'quando chega', 'cade meu pedido', 'preciso agendar'. Voce REFLETE o status; p/ mudar agendamento abra tarefa (abrir_tarefa area logistica).", input_schema: { type: "object", properties: { codparc: { type: "integer" }, nunota: { type: "integer" } }, required: [] } },
  { name: "gerar_planilha_carteira", description: "Gera uma PLANILHA (CSV/Excel) com a carteira COMPLETA do rep (todos os clientes: codigo, dias sem compra, faturamento 12m, clube, inadimplencia, cidade/uf e a ACAO recomendada por cliente) e retorna um LINK de download. Use quando pedirem planilha, relatorio/lista completa, ou plano cliente a cliente pra levar. Depois MANDE o link pro rep.", input_schema: { type: "object", properties: {}, required: [] } },
  { name: "abrir_tarefa", description: "Abre uma TAREFA na fila de execucao para uma ACAO que precisa ser feita no Sankhya/sistema por um HUMANO (voce NAO grava no Sankhya). Use quando o rep pedir algo que exige faturar/liberar/refazer pedido, liberar credito, vincular/corrigir cadastro, mudar tabela, corrigir nota/item/preco, emitir devolucao/abatimento, agendar retirada, bonificacao, ou app travando (TI). NAO use para consulta (isso voce responde direto). Escolha a AREA certa. Retorna o protocolo p/ voce passar ao rep.", input_schema: { type: "object", properties: { area: { type: "string", enum: ["execucao", "financeiro", "cadastro", "logistica", "faturamento", "ti", "comercial", "gestor"] }, tipo: { type: "string", description: "rotulo curto, ex 'faturar pedido', 'liberar credito', 'corrigir nota'" }, acao: { type: "string", description: "o que tem que ser feito, objetivo" }, detalhe: { type: "string", description: "contexto/dados (pedido, valor, motivo)" }, codparc: { type: "integer" }, cliente_nome: { type: "string" } }, required: ["area", "acao"] } },
];
async function runTool(sb: any, ctx: any, name: string, input: any): Promise<any> {
  try {
    if (name === "buscar_cliente") { const termo = String(input?.termo || "").trim(); const dig = digits(termo); const soDig = dig === termo.replace(/\s/g, ""); let q = sb.from("ghl_cliente").select("codparc, razao, cnpj, ticket, dias, situacao, classe, canal, ramo, rep, mix, compra_linhas, saldo_entregar, titulos_vencidos, score, resumo, crosssell, clube_saldo_pedir").limit(6); if (dig.length >= 11) q = q.ilike("cnpj", "%" + dig + "%"); else if (soDig && dig.length >= 2 && dig.length <= 7) q = q.eq("codparc", parseInt(dig)); else q = q.ilike("razao", "%" + termo + "%"); const { data } = await q; if (!data || !data.length) { let w = ""; if (dig.length >= 11) w = `REGEXP_REPLACE(P.CGC_CPF,'[^0-9]','') LIKE '%${dig}%'`; else if (soDig && dig.length >= 2 && dig.length <= 7) w = `P.CODPARC=${parseInt(dig)}`; else w = `UPPER(P.NOMEPARC) LIKE UPPER('%${termo.replace(/'/g, "''")}%')`; const sqlL = `SELECT * FROM (SELECT P.CODPARC, P.NOMEPARC, P.RAZAOSOCIAL, P.CGC_CPF, P.ATIVO, P.BLOQUEAR, P.CODVEND, (SELECT MAX(A.APELIDO) FROM TGFVEN A WHERE A.CODVEND=P.CODVEND) VENDEDOR, (SELECT TO_CHAR(MAX(CAB.DTNEG),'DD/MM/YYYY') FROM TGFCAB CAB WHERE CAB.CODPARC=P.CODPARC AND CAB.TIPMOV='V') ULT_FAT FROM TGFPAR P WHERE ${w} AND P.CODPARC NOT IN (1,68200)) WHERE ROWNUM<=6`; const { fields, rows, erro } = await skExec(sqlL); if (erro || !rows.length) return { encontrados: 0, aviso: "nao achei nem no espelho nem no Sankhya ao vivo por '" + termo + "'" }; const cs2 = rows.map((r) => { const o: any = {}; fields.forEach((f, i) => o[f] = r[i]); return { codparc: o.CODPARC, razao: o.RAZAOSOCIAL || o.NOMEPARC, nome: o.NOMEPARC, cnpj: o.CGC_CPF, ativo: o.ATIVO, bloquear: o.BLOQUEAR, rep: o.VENDEDOR, ultimo_faturamento: o.ULT_FAT ? ("em " + o.ULT_FAT) : "sem registro", fonte: "sankhya_ao_vivo" }; }); return { encontrados: cs2.length, clientes: cs2, ao_vivo: true }; } const cs = (data as any[]).map((c) => ({ ...c, ultimo_faturamento: c.dias != null ? ("ha " + c.dias + " dias") : "sem registro" })); return { encontrados: cs.length, clientes: cs }; }
    if (name === "pedido_cliente") { const cod = parseInt(input?.codparc || input?.termo); if (!cod) return { erro: "codparc invalido" }; const sql = `SELECT * FROM (SELECT CAB.NUNOTA, TO_CHAR(CAB.DTNEG,'DD/MM/YYYY') DATA, CAB.TIPMOV, CAB.STATUSNOTA, CAB.VLRNOTA, (SELECT MAX(T.DESCRTIPVENDA) FROM TGFTPV T WHERE T.CODTIPVENDA=CAB.CODTIPVENDA) TIPO_NEG FROM TGFCAB CAB WHERE CAB.CODPARC=${cod} AND CAB.TIPMOV IN ('P','V') ORDER BY CAB.DTNEG DESC, CAB.NUNOTA DESC) WHERE ROWNUM<=8`; const { rows, erro } = await skExec(sql); if (erro) return { erro }; if (!rows.length) return { encontrados: 0, aviso: "sem pedidos/notas p/ codparc " + cod }; const st = (s: any) => ({ A: "em aberto", L: "faturado", C: "cancelado" } as any)[s] || s; const tp = (t: any) => t === "V" ? "nota faturada" : t === "D" ? "devolucao" : "pedido"; const lista = rows.map((r) => ({ nunota: r[0], data: r[1], tipo: tp(r[2]), status: st(r[3]), valor: r[4], prazo_pagamento: r[5] })); const real = lista.find((x) => !/bonific|credito|cortesia|brinde/i.test(String(x.prazo_pagamento || ""))); return { encontrados: lista.length, ultimo: lista[0], ultimo_pedido_com_prazo: real || null, pedidos: lista }; }
    if (name === "boleto_cliente") { const cod = parseInt(input?.codparc); if (!cod) return { erro: "codparc invalido" }; const sql = `SELECT * FROM (SELECT NUFIN, NUNOTA, TO_CHAR(DTVENC,'DD/MM/YYYY') VENC, VLRDESDOB, NOSSONUM, LINHADIGITAVEL, CODBCO, CASE WHEN TRUNC(DTVENC) < TRUNC(SYSDATE) THEN 'vencido' ELSE 'a_vencer' END SITUACAO FROM TGFFIN WHERE CODPARC=${cod} AND RECDESP=1 AND PROVISAO='N' AND DHBAIXA IS NULL ORDER BY DTVENC) WHERE ROWNUM<=15`; const { rows, erro } = await skExec(sql); if (erro) return { erro }; if (!rows.length) return { encontrados: 0, vencidos: 0, a_vencer: 0, aviso: "sem titulo a receber em aberto p/ esse cliente" }; const lista = rows.map((r) => ({ nufin: r[0], nunota: r[1], vencimento: r[2], valor: r[3], nosso_numero: r[4], linha_digitavel: r[5] || null, banco: r[6], situacao: r[7], boleto_emitido: !!r[5] })); const venc = lista.filter((x) => x.situacao === "vencido").length; const semb = lista.filter((x) => !x.linha_digitavel).length; return { encontrados: lista.length, vencidos: venc, a_vencer: lista.length - venc, titulos: lista, obs: (venc ? (venc + " vencido(s). ") : "NENHUM vencido - a_vencer e normal. ") + (semb ? (semb + " sem linha digitavel = boleto nao emitido, encaminhar ao financeiro. ") : "") + "Cada titulo traz o NUNOTA: use consultar_sankhya p/ pedido/faturamento/entrega." }; }
    if (name === "consultar_conhecimento") { const termo = String(input?.termo || "").trim(); if (!termo) return { erro: "termo vazio" }; const { data, error } = await sb.rpc("buscar_conhecimento", { q: termo }); if (error) return { erro: error.message }; if (!data || !data.length) return { encontrados: 0, aviso: "nada na base p/ '" + termo + "'" }; return { encontrados: data.length, conhecimento: (data as any[]).map((d) => ({ sistema: d.sistema, topico: d.topico, titulo: d.titulo, texto: String(d.conteudo).slice(0, 3000) })) }; }
    if (name === "consultar_sankhya") { const c = checarSql(input?.sql); if (!c.ok) return { erro: c.motivo, restrito: true }; const { fields, rows, erro } = await skExec(c.sql!); if (erro) return { erro }; const objs = rows.slice(0, 60).map((r) => { const o: any = {}; fields.forEach((f, i) => o[f || ("c" + i)] = r[i]); return o; }); return { colunas: fields, qtd: objs.length, linhas: objs }; }
    if (name === "produtos") { const termo = String(input?.termo || "").trim(); if (!termo) return { erro: "termo vazio" }; const like = "%" + termo + "%"; const { data } = await sb.from("produto_web").select("categoria, nome, url, ramo").eq("ativo", true).or(`nome.ilike.${like},categoria.ilike.${like},ramo.ilike.${like}`).limit(6); if (!data || !data.length) return { encontrados: 0, aviso: "nenhum produto" }; return { encontrados: data.length, produtos: data, dica: "mande o url; sem preco." }; }
    if (name === "saldos_cliente") { const cod = parseInt(input?.codparc); if (!cod) return { erro: "codparc invalido" }; const { data } = await sb.from("saldo_pedido").select("nunota, nome, valorpend, pct_atend, atende, dtneg").eq("codparc", cod).gte("valorpend", 1000).order("valorpend", { ascending: false }).limit(30); const total = (data || []).reduce((a: number, bb: any) => a + (Number(bb.valorpend) || 0), 0); return { codparc: cod, qtd: (data || []).length, total_saldo: Math.round(total), saldos: data || [] }; }
    if (name === "cobranca_cliente") { const cod = parseInt(input?.codparc); if (!cod) return { erro: "codparc invalido" }; const sql = `SELECT COUNT(*) N, NVL(SUM(CASE WHEN TRUNC(DTVENC)<TRUNC(SYSDATE) THEN 1 ELSE 0 END),0) N_VENC, NVL(SUM(CASE WHEN TRUNC(DTVENC)<TRUNC(SYSDATE) THEN VLRDESDOB ELSE 0 END),0) VENCIDO, NVL(SUM(VLRDESDOB),0) TOTAL, TO_CHAR(MIN(CASE WHEN TRUNC(DTVENC)<TRUNC(SYSDATE) THEN DTVENC END),'DD/MM/YYYY') VENC_ANTIGO, NVL(TRUNC(SYSDATE)-MIN(CASE WHEN TRUNC(DTVENC)<TRUNC(SYSDATE) THEN TRUNC(DTVENC) END),0) MAIOR_ATRASO FROM TGFFIN WHERE CODPARC=${cod} AND RECDESP=1 AND PROVISAO='N' AND DHBAIXA IS NULL`; const { fields, rows, erro } = await skExec(sql); if (erro) return { erro }; if (!rows.length) return { codparc: cod, ao_vivo: true, vencido: false, aviso: "sem titulo a receber em aberto" }; const o: any = {}; fields.forEach((f, i) => o[f] = rows[0][i]); const nv = Number(o.N_VENC || 0); return { codparc: cod, ao_vivo: true, vencido: nv > 0, n_titulos_aberto: Number(o.N || 0), n_vencidos: nv, valor_vencido: Math.round(Number(o.VENCIDO || 0)), total_aberto: Math.round(Number(o.TOTAL || 0)), maior_atraso_dias: Number(o.MAIOR_ATRASO || 0), venc_mais_antigo: o.VENC_ANTIGO || null, obs: nv ? (nv + " titulo(s) vencido(s) - travar venda ate resolver a cobranca") : "nenhum vencido - a_vencer e normal" }; }
    if (name === "minha_carteira") { const cv = ctx.codvend; const { data } = await sb.from("roteiro_cliente").select("codparc, nome, dias, fat12m, clube_saldo, inad, cidade, uf").eq("codvend", cv).limit(5000); const rows = (data || []).filter((r: any) => Number(r.codparc) !== 1 && Number(r.codparc) !== 68200); const parados = rows.filter((r: any) => Number(r.dias) >= 60); const inad = rows.filter((r: any) => r.inad); const clube = rows.filter((r: any) => Number(r.clube_saldo) > 0); const lista = [...rows].sort((a: any, bb: any) => Number(bb.fat12m || 0) - Number(a.fat12m || 0)).map((r: any) => ({ codparc: r.codparc, cliente: r.nome, dias_sem_compra: r.dias, faturamento_12m: Math.round(Number(r.fat12m) || 0), inadimplente: !!r.inad, clube_saldo: Math.round(Number(r.clube_saldo) || 0), cidade: r.cidade, uf: r.uf })); const atencao = [...parados].sort((a: any, bb: any) => Number(bb.dias) - Number(a.dias)).slice(0, 8).map((r: any) => ({ codparc: r.codparc, nome: r.nome, dias: r.dias })); return { total_clientes: rows.length, parados_60d: parados.length, inadimplentes: inad.length, clube_com_saldo: clube.length, mais_atencao: atencao, lista_completa: lista }; }
    if (name === "abrir_tarefa") { const area = String(input?.area || "execucao").toLowerCase().trim(); const acao = String(input?.acao || "").trim(); if (!acao) return { erro: "acao vazia" }; const row: any = { area, tipo: (input?.tipo || null), acao: acao.slice(0, 500), detalhe: String(input?.detalhe || "").slice(0, 1500) || null, rep: ctx.rep || null, codvend: ctx.codvend || null, cliente_nome: input?.cliente_nome || null, codparc: input?.codparc ? parseInt(input.codparc) : null, contact_id: ctx.contact_id || null, origem: "nina-rep" }; const { data, error } = await sb.from("copiloto_tarefas").insert(row).select("id").maybeSingle(); if (error) return { erro: error.message }; return { ok: true, protocolo: data?.id, area, aviso: "tarefa #" + data?.id + " aberta na fila de execucao (area " + area + ") - passe esse protocolo pro rep" }; }
    if (name === "pedidos_pendentes") {
      const cv = ctx.codvend; if (!cv) return { erro: "rep sem codvend" };
      const sql = `SELECT G, NUNOTA, DT, NOME, VLR, SF FROM (
        SELECT 'A_FATURAR' G, CAB.NUNOTA, TO_CHAR(CAB.DTNEG,'DD/MM/YYYY') DT, SUBSTR(PAR.NOMEPARC,1,40) NOME, CAB.VLRNOTA VLR, NVL(CAB.AD_STATUFORCA,'-') SF
          FROM TGFCAB CAB JOIN TGFPAR PAR ON PAR.CODPARC=CAB.CODPARC
          WHERE CAB.CODVEND=${cv} AND CAB.TIPMOV='P' AND CAB.STATUSNOTA='L' AND CAB.PENDENTE='S' AND CAB.DTNEG>=ADD_MONTHS(SYSDATE,-6) AND CAB.CODPARC NOT IN (1,68200)
        UNION ALL
        SELECT 'A_LIBERAR' G, CAB.NUNOTA, TO_CHAR(CAB.DTNEG,'DD/MM/YYYY') DT, SUBSTR(PAR.NOMEPARC,1,40) NOME, CAB.VLRNOTA VLR, NVL(CAB.AD_STATUFORCA,'-') SF
          FROM TGFCAB CAB JOIN TGFPAR PAR ON PAR.CODPARC=CAB.CODPARC
          WHERE CAB.CODVEND=${cv} AND CAB.TIPMOV='P' AND CAB.STATUSNOTA='A' AND CAB.PENDENTE='S' AND CAB.DTNEG>=ADD_MONTHS(SYSDATE,-4) AND CAB.CODPARC NOT IN (1,68200)
        UNION ALL
        SELECT 'FATURADO_MES' G, CAB.NUNOTA, TO_CHAR(NVL(CAB.DTFATUR,CAB.DTNEG),'DD/MM/YYYY') DT, SUBSTR(PAR.NOMEPARC,1,40) NOME, CAB.VLRNOTA VLR, '-' SF
          FROM TGFCAB CAB JOIN TGFPAR PAR ON PAR.CODPARC=CAB.CODPARC
          WHERE CAB.CODVEND=${cv} AND CAB.TIPMOV='V' AND CAB.STATUSNOTA='L' AND TRUNC(NVL(CAB.DTFATUR,CAB.DTNEG))>=TRUNC(SYSDATE,'MM') AND CAB.CODPARC NOT IN (1,68200)
      ) WHERE ROWNUM <= 500`;
      const { rows, erro } = await skExec(sql); if (erro) return { erro };
      const B: Record<string, any[]> = { A_FATURAR: [], A_LIBERAR: [], EM_ELABORACAO: [], FATURADO_MES: [] };
      for (const r of rows) { let g = String(r[0]); const sf = String(r[5] || ""); if (g === "A_LIBERAR" && /ELAB/i.test(sf)) g = "EM_ELABORACAO"; (B[g] || (B[g] = [])).push({ nunota: r[1], data: r[2], cliente: r[3], valor: Math.round(Number(r[4]) || 0), etapa: sf }); }
      const resumo = (arr: any[]) => ({ qtd: arr.length, valor_total: arr.reduce((a, x) => a + x.valor, 0), itens: arr.sort((a, b) => b.valor - a.valor).slice(0, 15) });
      return { rep: ctx.rep, hoje: hojeBRT(), a_faturar: resumo(B.A_FATURAR), a_liberar: resumo(B.A_LIBERAR), em_elaboracao: resumo(B.EM_ELABORACAO), faturado_mes: resumo(B.FATURADO_MES), obs: "SO da carteira DELE (codvend " + cv + "), recente, sem intercompany. A_FATURAR=pedido liberado aguardando a nota (a pendencia esta no faturamento). A_LIBERAR=pedido aguardando revisao/aprovacao interna (etapa em 'etapa'). EM_ELABORACAO=rep/cliente ainda montando o pedido. FATURADO_MES=notas emitidas no mes atual. Fale por NOME+valor+data, some os totais, e diga ONDE esta a pendencia de cada bloco. Se algum bloco vier 0, diga que esta zerado (nao invente)." };
    }
    if (name === "preco_produto") {
      const cod = parseInt(input?.codparc || ""); const prod = String(input?.produto || input?.termo || "").trim();
      if (!cod) return { erro: "preciso do codparc do cliente p/ saber a tabela dele" }; if (!prod) return { erro: "qual produto?" };
      const dig = prod.replace(/\D/g, ""); const ehCod = !!dig && dig === prod.replace(/\s/g, "") && dig.length <= 6;
      const filtro = ehCod ? `P.CODPROD=${parseInt(dig)}` : `UPPER(P.DESCRPROD) LIKE UPPER('%${prod.replace(/'/g, "''")}%')`;
      const sql = `SELECT * FROM (SELECT P.CODPROD, SUBSTR(P.DESCRPROD,1,50) PROD, E.VLRVENDA, T.CODTAB, T.NOMEPARC FROM (SELECT CODPARC, NOMEPARC, CODTAB FROM TGFPAR WHERE CODPARC=${cod}) T JOIN TGFEXC E ON E.NUTAB=T.CODTAB JOIN TGFPRO P ON P.CODPROD=E.CODPROD WHERE P.ATIVO='S' AND E.VLRVENDA>0 AND ${filtro} ORDER BY P.DESCRPROD) WHERE ROWNUM<=15`;
      const { fields, rows, erro } = await skExec(sql); if (erro) return { erro };
      if (!rows.length) return { encontrados: 0, aviso: "sem preco na tabela do cliente p/ '" + prod + "' (produto inativo, sem preco nessa tabela, ou nome nao bateu)" };
      const ix = (n: string) => fields.indexOf(n); const itens = rows.map((r) => ({ codprod: r[ix("CODPROD")], produto: r[ix("PROD")], preco: Number(r[ix("VLRVENDA")]), tabela: r[ix("CODTAB")] }));
      return { cliente_codparc: cod, cliente: rows[0][ix("NOMEPARC")], tabela_do_cliente: itens[0].tabela, ao_vivo: true, itens, obs: "Preco JA e o da TABELA DESSE CLIENTE (CODTAB " + itens[0].tabela + "), atacado - nao e varejo/site. Se vieram varios itens, confirme qual produto ele quer." };
    }
    if (name === "credito_cliente") {
      const cod = parseInt(input?.codparc || ""); if (!cod) return { erro: "codparc invalido" };
      const sql = `SELECT PAR.NOMEPARC, PAR.LIMCRED, PAR.BLOQUEAR, PAR.MOTBLOQ, NVL((SELECT SUM(F.VLRDESDOB) FROM TGFFIN F WHERE F.CODPARC=PAR.CODPARC AND F.RECDESP=1 AND F.PROVISAO='N' AND F.DHBAIXA IS NULL),0) ABERTO, NVL((SELECT SUM(F.VLRDESDOB) FROM TGFFIN F WHERE F.CODPARC=PAR.CODPARC AND F.RECDESP=1 AND F.PROVISAO='N' AND F.DHBAIXA IS NULL AND TRUNC(F.DTVENC)<TRUNC(SYSDATE)),0) VENCIDO FROM TGFPAR PAR WHERE PAR.CODPARC=${cod}`;
      const { fields, rows, erro } = await skExec(sql); if (erro) return { erro }; if (!rows.length) return { erro: "cliente nao encontrado" };
      const o: any = {}; fields.forEach((f, i) => o[f] = rows[0][i]);
      const lim = Number(o.LIMCRED || 0), aberto = Math.round(Number(o.ABERTO || 0)), venc = Math.round(Number(o.VENCIDO || 0)); const bloq = String(o.BLOQUEAR || "N") === "S"; const disp = Math.round(lim - aberto); const pode = !bloq && venc === 0 && disp >= 0;
      return { codparc: cod, cliente: o.NOMEPARC, ao_vivo: true, bloqueado: bloq, motivo_bloqueio: bloq ? (o.MOTBLOQ || "sem motivo informado") : null, limite_credito: Math.round(lim), saldo_em_aberto: aberto, valor_vencido: venc, credito_disponivel: disp, pode_comprar: pode, obs: bloq ? "CLIENTE BLOQUEADO - nao vender, encaminhar" : venc > 0 ? ("TEM R$ " + venc + " VENCIDO - regularizar antes de vender (regra: nao vende a quem tem vencido)") : disp < 0 ? ("estourou o limite: aberto R$ " + aberto + " > limite R$ " + Math.round(lim)) : "liberado p/ comprar dentro do limite disponivel R$ " + disp };
    }
    if (name === "estoque_produto") {
      const prod = String(input?.produto || input?.termo || "").trim(); if (!prod) return { erro: "qual produto?" };
      const dig = prod.replace(/\D/g, ""); const ehCod = !!dig && dig === prod.replace(/\s/g, "") && dig.length <= 6;
      const filtro = ehCod ? `P.CODPROD=${parseInt(dig)}` : `UPPER(P.DESCRPROD) LIKE UPPER('%${prod.replace(/'/g, "''")}%')`;
      const sql = `SELECT * FROM (SELECT P.CODPROD, SUBSTR(P.DESCRPROD,1,50) PROD, NVL(SUM(E.ESTOQUE-E.RESERVADO),0) DISP FROM TGFPRO P LEFT JOIN TGFEST E ON E.CODPROD=P.CODPROD AND E.TIPO='P' WHERE P.ATIVO='S' AND ${filtro} GROUP BY P.CODPROD, P.DESCRPROD ORDER BY P.DESCRPROD) WHERE ROWNUM<=15`;
      const { fields, rows, erro } = await skExec(sql); if (erro) return { erro }; if (!rows.length) return { encontrados: 0, aviso: "produto nao encontrado por '" + prod + "'" };
      const ix = (n: string) => fields.indexOf(n); const itens = rows.map((r) => { const d = Math.floor(Number(r[ix("DISP")]) || 0); return { codprod: r[ix("CODPROD")], produto: r[ix("PROD")], disponivel: d, tem: d > 0 }; });
      return { ao_vivo: true, itens, obs: "disponivel = estoque proprio menos reservado. 0 ou negativo = NAO prometer, confirmar com a fabrica. Nunca prometa quantidade sem estoque." };
    }
    if (name === "entrega_cliente") {
      const cod = parseInt(input?.codparc || ""); const nun = parseInt(input?.nunota || ""); if (!cod && !nun) return { erro: "preciso do codparc ou do nunota" };
      const w = nun ? `V.NUNOTA=${nun}` : `V.CODPARC=${cod}`;
      const sql = `SELECT * FROM (SELECT V.NUNOTA, SUBSTR(V.NOMEPARC,1,32) CLIENTE, V.STATUSPEDIDO, V.DIAS, TO_CHAR(V.DTPREVENT,'DD/MM/YYYY') PREVENT, V.NOME_TRANSPORTADORA, ROUND(V.VLRSALDO) VLRSALDO, V.NECESSITA_AGEND, V.AGENDAMENTO_DESC, V.ORDEMCARGA, TO_CHAR(AG.NOVADATA,'DD/MM/YYYY') AGENDADA, AG.STATUS AGSTATUS, AG.FALOUCOM FROM VW_PEDIDOS_ENTREGAR V LEFT JOIN AD_TSIAGENENT AG ON AG.NUNOTA=V.NUNOTA WHERE ${w} ORDER BY V.NUNOTA DESC) WHERE ROWNUM<=12`;
      const { fields, rows, erro } = await skExec(sql); if (erro) return { erro }; if (!rows.length) return { encontrados: 0, aviso: "nada na fila de entrega/expedicao p/ esse " + (nun ? "pedido" : "cliente") + " (ja entregue, ou ainda nao faturado)" };
      const itens = rows.map((r) => { const o: any = {}; fields.forEach((f, i) => o[f] = r[i]); return o; });
      return { ao_vivo: true, qtd: itens.length, entregas: itens, obs: "STATUSPEDIDO=situacao na expedicao; PREVENT=previsao de entrega; AGENDADA/AGSTATUS=agendamento (AD_TSIAGENENT); NECESSITA_AGEND indica se precisa agendar. Voce REFLETE o status - p/ reagendar/mudar abra tarefa (abrir_tarefa, area logistica)." };
    }
    if (name === "gerar_planilha_carteira") { const cv = ctx.codvend; const { data } = await sb.from("roteiro_cliente").select("codparc, nome, dias, fat12m, clube_saldo, inad, cidade, uf").eq("codvend", cv).limit(5000); const rows = (data || []).filter((r: any) => Number(r.codparc) !== 1 && Number(r.codparc) !== 68200).sort((a: any, bb: any) => Number(bb.fat12m || 0) - Number(a.fat12m || 0)); if (!rows.length) return { erro: "sem carteira p/ esse rep" }; const acaoDe = (r: any) => r.inad ? "COBRANCA - resolver inadimplencia antes de vender" : Number(r.clube_saldo) > 0 ? "CLUBE - confirmar retirada (venda ja paga)" : Number(r.dias) >= 60 ? ("REATIVAR - " + r.dias + " dias parado") : Number(r.dias) <= 20 ? "RECOMPRA - comprou recente" : "VISITA/CONTATO"; const q = String.fromCharCode(34); const esc = (v: any) => q + String(v == null ? "" : v).split(q).join(q + q) + q; const head = ["Cliente", "Codigo", "Dias sem compra", "Faturamento 12m", "Clube saldo", "Inadimplente", "Cidade", "UF", "O QUE FAZER"]; const linhas = [head.map(esc).join(",")]; for (const r of rows) linhas.push([r.nome, r.codparc, r.dias, Math.round(Number(r.fat12m) || 0), Math.round(Number(r.clube_saldo) || 0), r.inad ? "SIM" : "", r.cidade, r.uf, acaoDe(r)].map(esc).join(",")); const csv = String.fromCharCode(65279) + linhas.join(String.fromCharCode(13, 10)); const path = "carteira_" + cv + "_" + Date.now() + ".csv"; const up = await sb.storage.from("planilhas").upload(path, new Blob([csv], { type: "text/csv" }), { contentType: "text/csv; charset=utf-8", upsert: true }); if (up.error) return { erro: "upload: " + up.error.message }; const url = Deno.env.get("SUPABASE_URL") + "/storage/v1/object/public/planilhas/" + path; return { ok: true, url, total_clientes: rows.length, aviso: "Planilha pronta com " + rows.length + " clientes. MANDE este link pro rep (abre no Excel/celular): " + url }; }
    return { erro: "ferramenta desconhecida" };
  } catch (e) { return { erro: String(e) }; }
}
async function anthropic(system: string, messages: any[], hard = false): Promise<any> { const key = Deno.env.get("ANTHROPIC_API_KEY"); if (!key) throw new Error("sem ANTHROPIC_API_KEY"); const r = await fetch("https://api.anthropic.com/v1/messages", { method: "POST", headers: { "x-api-key": key, "anthropic-version": "2023-06-01", "content-type": "application/json" }, body: JSON.stringify(hard ? { model: MODELO_HARD, max_tokens: 8000, system, tools: TOOLS, messages } : { model: MODELO, max_tokens: 1500, temperature: 0.6, system, tools: TOOLS, messages }) }); if (!r.ok) throw new Error("anthropic " + r.status + " " + (await r.text()).slice(0, 300)); return await r.json(); }
async function enviarWhatsapp(contact_id: string | null, fone: string, texto: string, instancia?: string) { const url = Deno.env.get("SUPABASE_URL")!; const key = SRK; const body: any = { canal: "whatsapp", texto }; if (contact_id) body.contact_id = contact_id; else body.fone = fone; if (instancia) body.instancia = instancia; const r = await fetch(url + "/functions/v1/campanhas-enviar", { method: "POST", headers: { "Authorization": "Bearer " + key, "Content-Type": "application/json" }, body: JSON.stringify(body) }); return await r.json().catch(() => ({ ok: false })); }
async function licoesTxt(sb: any): Promise<string> { try { const { data } = await sb.from("copiloto_licoes").select("licao").eq("ativo", true).order("id"); const ls = (data || []).map((r: any) => "- " + r.licao); return ls.length ? ("\n\nLICOES DO GESTOR (regras que o Ricardo ENSINOU - tem PRIORIDADE, siga a risca):\n" + ls.join("\n")) : ""; } catch (_e) { return ""; } }
Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  const alertas: any[] = [];
  const sb = createClient(Deno.env.get("SUPABASE_URL")!, SRK);
  async function flushAlertas(cfg: any, fone: string, codvend: number | null, instancia: string | null, rep: string, texto: string, reply?: string) {
    if (!alertas.length) return;
    try { await sb.from("copiloto_alertas").insert(alertas.map((a) => ({ fone, codvend, instancia, tipo: a.tipo, detalhe: a.detalhe, texto_contato: String(texto || "").slice(0, 500), reply: (reply || "").slice(0, 500) }))); } catch (_e) { /* */ }
    try { if (cfg && String(cfg.alerta_ativo || "nao").toLowerCase() === "sim" && cfg.alerta_fone) { const tipos = [...new Set(alertas.map((a) => a.tipo))]; const msg = "⚠️ Copiloto (" + tipos.join(", ") + ")\nRep: " + (rep || "") + " | inst: " + (instancia || "") + "\nDisse: " + String(texto || "").slice(0, 180) + "\nIA: " + String(reply || "").slice(0, 180); await enviarWhatsapp(null, String(cfg.alerta_fone), msg, cfg.alerta_instancia || instancia || undefined); } } catch (_e) { /* */ }
  }
  try {
    const secret = Deno.env.get("COPILOTO_SECRET"); if (secret && req.headers.get("x-copiloto-secret") !== secret) return j({ erro: "nao autorizado" }, 401);
    const p = new URL(req.url).searchParams; const b = await req.json().catch(() => ({}));
    if (b.modo_resolver === true) {
      const cod = parseInt(b.codparc || "") || null; const perg = String(b.texto || b.pergunta || "").trim(); const histR = Array.isArray(b.historico) ? b.historico : [];
      if (!perg) return j({ ok: false, erro: "sem pergunta" });
      let nomeCli = ""; if (cod) { try { const { data } = await sb.from("ghl_cliente").select("razao").eq("codparc", cod).maybeSingle(); if (data) nomeCli = data.razao || ""; } catch (_e) { /* */ } }
      const { data: skR } = await sb.from("copiloto_skills").select("nome,conteudo").eq("ativo", true);
      const temaR = detectarTema(perg); const ordemR = (n: string) => n === temaR ? 0 : n === "campanhas" ? 1 : 2; const playbookR = (skR || []).sort((a: any, b: any) => ordemR(a.nome) - ordemR(b.nome)).map((r: any) => "[" + String(r.nome).toUpperCase() + "]\n" + r.conteudo).join("\n\n"); const licR = await licoesTxt(sb);
      const sysR = `Voce e a Nina, o cerebro comercial da Nitron, resolvendo INTERNAMENTE uma pendencia que a assistente ainda NAO resolveu. Use as ferramentas (Sankhya ao vivo + consultar_conhecimento) e o MAPA DE VINCULOS para produzir a RESPOSTA PRONTA com o dado REAL, em NOME de cliente/produto (nunca codigo cru). ${cod ? ("O cliente e " + (nomeCli || ("codparc " + cod)) + " [codparc " + cod + "].") : "Se nao souber o codparc, identifique por nome/CNPJ."} Restricoes: NUNCA invente; sem RH/producao/pagamentos; nao cite preco de PRODUTO ao cliente. Se depender de decisao humana (desconto/negociacao/reclamacao/avaria/troca) ou faltar dado, comece com \"NAO_RESOLVIVEL:\" + motivo + para quem encaminhar. Se resolvivel, comece com \"RESPOSTA:\" + texto pronto. HOJE e ${hojeBRT()} (data atual real; datas de 2026 sao normais, nao futuras). Para pedidos a faturar/a liberar de um representante, filtre CAB.CODVEND do rep e DTNEG recente (nunca anos atras).` + (playbookR ? ("\n\nPLAYBOOK:\n" + playbookR) : "") + licR;
      const msgsR: any[] = [...histR.slice(-6), { role: "user", content: perg }];
      let repR = ""; for (let i = 0; i < 6; i++) { const resp = await anthropic(sysR, msgsR, true); const bl = resp.content || []; msgsR.push({ role: "assistant", content: bl }); const tus = bl.filter((x: any) => x.type === "tool_use"); if (resp.stop_reason !== "tool_use" || !tus.length) { repR = bl.filter((x: any) => x.type === "text").map((x: any) => x.text).join("\n").trim(); break; } const rs: any[] = []; for (const tu of tus) { const out = await runTool(sb, { codvend: 0, rep: "" }, tu.name, tu.input); rs.push({ type: "tool_result", tool_use_id: tu.id, content: JSON.stringify(out).slice(0, 8000) }); } msgsR.push({ role: "user", content: rs }); }
      const naoR = /^\s*NAO_RESOLVIVEL/i.test(repR); const limpo = repR.replace(/^\s*(RESPOSTA:|NAO_RESOLVIVEL:)\s*/i, "").trim();
      return j({ ok: true, modo_resolver: true, codparc: cod, tema: temaR, resolvivel: !naoR, resposta: naoR ? "" : limpo, encaminhar: naoR ? limpo : "", bruto: repR });
    }
    const dry = p.get("dry") === "1" || b.dry === true; const modo = String(p.get("modo") || b.modo || "").toLowerCase();
    const rawText = pickText(b); const parsed = parseInstance(rawText); const instSource = parsed.inst; let texto = parsed.clean;
    const fone = String(b.fone || b.phone || b.contact_phone || b?.customData?.Fone || b?.contact?.phone || "").trim();
    const contact_id = (b.contact_id || b.contactId || b?.customData?.contact_id || b?.contact?.id || null) as string | null;
    const instBody = b.instancia || b.instance || undefined;
    const anexo = b.attachment || b.attachments || b?.customData?.attachment || b?.customData?.attachments || b?.message?.attachments || b?.Attachment || "";
    const midia = urlAnexo(anexo); const ehPtt = norm(texto) === "ptt"; const temMidia = !!midia || ehPtt;
    try { await sb.from("copiloto_debug").insert({ fone: String(fone || ""), texto_extraido: (temMidia ? "[midia] " : "") + (instSource ? (texto + " | inst:" + instSource) : texto), raw: b }); } catch (_e) { /* */ }
    if (!texto && !temMidia) return j({ ok: true, skip: "sem texto/midia", fone });
    const { data: cfgRows } = await sb.from("copiloto_config").select("*"); const cfg: Record<string, string> = {}; (cfgRows || []).forEach((r: any) => cfg[r.chave] = r.valor);
    if ((cfg.copiloto_ativo || "sim").toLowerCase() === "nao") return j({ ok: true, desligado: true, enviado: false });
    const INST = (cfg.instancia_padrao || "").trim(); const pilotoApenas = (cfg.piloto_apenas || "sim").toLowerCase() === "sim"; const nivel = parseInt(cfg.copiloto_nivel || "2") || 2;
    const s10 = d10(fone);
    const treinadores = String(cfg.treinador_fones || "").split(",").map((x) => d10(x)).filter(Boolean);
    if (texto && s10 && treinadores.includes(s10)) {
      const tl = norm(texto);
      if (/^(aprovar|rejeitar)\b/.test(tl)) { const rej = tl.indexOf("rejeitar") === 0; const idsRaw = texto.replace(/^\s*(aprovar|rejeitar)\s*/i, "").trim(); const instA = instBody || instSource || cfg.instancia_padrao || "Nina"; try { const rr = await fetch(Deno.env.get("SUPABASE_URL") + "/functions/v1/copiloto-aprender?acao=" + (rej ? "rejeitar" : "aprovar") + "&ids=" + encodeURIComponent(idsRaw), { method: "POST", headers: { Authorization: "Bearer " + SRK, "Content-Type": "application/json" }, body: "{}" }); const dd = await rr.json().catch(() => ({})); if (!dry) await enviarWhatsapp(contact_id, fone, (rej ? "Rejeitei " : "Aprovei e ja apliquei ") + (dd.processados || 0) + " item(ns) do aprendizado. Ja valem pra Nina.", instA); return j({ ok: true, aprovacao: dd }); } catch (e) { return j({ ok: false, erro: String(e) }); } }
      const { data: estT } = await sb.from("copiloto_treino_estado").select("ativo").eq("fone", s10).maybeSingle();
      const emTreino = estT?.ativo === true;
      const instT = instBody || instSource || cfg.instancia_padrao || "Nina";
      if (/^(modo treino|treinar|treino on|\/treino|ativar treino|modo treinamento|entrar em treino)$/.test(tl)) { await sb.from("copiloto_treino_estado").upsert({ fone: s10, ativo: true, atualizado: new Date().toISOString() }); if (!dry) await enviarWhatsapp(contact_id, fone, "Modo treino LIGADO. Me diz a correcao ou a regra que eu aprendo (uma por mensagem). Quando terminar, manda 'fim treino'.", instT); return j({ ok: true, treino: "ligado" }); }
      if (emTreino && /^(fim treino|sair treino|treino off|encerrar treino|voltar ao normal|fim do treino|sair do treino|acabou o treino)$/.test(tl)) { await sb.from("copiloto_treino_estado").upsert({ fone: s10, ativo: false, atualizado: new Date().toISOString() }); if (!dry) await enviarWhatsapp(contact_id, fone, "Modo treino desligado, voltei ao normal. As licoes que voce me deu ja valem.", instT); return j({ ok: true, treino: "desligado" }); }
      if (emTreino) { await sb.from("copiloto_licoes").insert({ licao: texto.slice(0, 1000), ativo: true, criado_por: s10 }); if (!dry) await enviarWhatsapp(contact_id, fone, "Aprendido: \"" + texto.slice(0, 160) + "\". Manda outra, ou 'fim treino' pra voltar.", instT); return j({ ok: true, treino: "licao_salva" }); }
    }
    const { data: aiRows } = await sb.from("assistente_instancia").select("nome,instancia,fone,ativo").eq("ativo", true); const AI_MAP: Record<string, any> = {}; (aiRows || []).forEach((r: any) => AI_MAP[norm(r.nome)] = r);
    let rep: any = null; let fromPilot = false;
    if (s10.length >= 8) { const { data: pil } = await sb.from("copiloto_piloto").select("*").eq("ativo", true); const hit = (pil || []).find((x: any) => d10(x.fone) === s10); if (hit) { rep = { codvend: Number(hit.codvend), rep: hit.nome }; fromPilot = true; } }
    if (!rep) { const fk = fk8(fone); if (fk) { const { data: reps } = await sb.from("snap_rep").select("codvend, rep, celular, fone_parc, assistente").limit(2000); const m = (reps || []).find((r: any) => fk8(r.celular) === fk || fk8(r.fone_parc) === fk); if (m) rep = { codvend: Number(m.codvend), rep: m.rep, assistente: m.assistente }; } }
    if (!rep) return j({ ok: true, rep: null, escalonar: true, enviado: false, reply: `Oi! Aqui e o time comercial da Nitron. Ja peco pra um colega falar com voce, ta?` });
    if (pilotoApenas && !fromPilot) return j({ ok: true, skip: "fora do piloto", rep: rep.rep });
    const fora = foraHorarioComercial();
    const autoList = String(cfg.auto_atendimento_inst || cfg.nome_assistente || "Nina").split(",").map((x) => norm(x)).filter(Boolean);
    const ehAuto = !!(instSource && autoList.includes(norm(instSource)));
    if (!ehAuto) {
      if (modo === "ia") { if (fora) return j({ ok: true, skip: "fora do horario — W1 responde na hora", fora, rep: rep.rep }); }
      else { if (!fora) return j({ ok: true, skip: "horario comercial — assistente primeiro", fora, rep: rep.rep, piloto: fromPilot }); }
    }
    let assistNome: string | null = null;
    if (fromPilot) { assistNome = (rep.assistente as string) || null; if (!assistNome && rep.codvend != null) { const { data: sr } = await sb.from("snap_rep").select("assistente").eq("codvend", rep.codvend).maybeSingle(); assistNome = sr?.assistente || null; } if (!assistNome && instSource && AI_MAP[norm(instSource)]) assistNome = AI_MAP[norm(instSource)].nome; }
    else { if (instSource && AI_MAP[norm(instSource)]) assistNome = AI_MAP[norm(instSource)].nome; if (!assistNome) { assistNome = (rep.assistente as string) || null; if (!assistNome && rep.codvend != null) { const { data: sr } = await sb.from("snap_rep").select("assistente").eq("codvend", rep.codvend).maybeSingle(); assistNome = sr?.assistente || null; } } }
    const aRow = assistNome ? AI_MAP[norm(assistNome)] : null; const personaNome = aRow ? prim(assistNome) : null; const instancia: string | undefined = instBody || (aRow ? aRow.instancia : (instSource || INST || undefined)); const persona = aRow ? "assistente" : "neutro"; const ehRep = fromPilot; const instKey = fromPilot ? ("rep:" + rep.codvend) : norm(instSource || instancia || "default");
    let audio = false; let imagem = false;
    if (temMidia) { const base = midia.split("?")[0]; const ehImg = /\.(jpg|jpeg|png|webp|gif|bmp|heic)$/i.test(base) || /\/image\//i.test(midia); const ehAudio = ehPtt || /\.(ogg|oga|opus|mp3|mpeg|m4a|mp4|wav|amr|aac|webm|flac)$/i.test(base) || /\/audio\//i.test(midia); if (ehAudio && midia && OAI) { const tr = await transcrever(midia); if (tr) { texto = (ehPtt || !texto ? "" : texto + " ") + tr; audio = true; } } else if (ehImg || (midia && !texto)) { const desc = await verImagem(midia); if (desc) { texto = (texto && !ehPtt ? texto + " " : "") + "[o contato enviou uma imagem — conteudo: " + desc + "]"; imagem = true; } } if (norm(texto) === "ptt") texto = ""; }
    if (!texto) { alertas.push({ tipo: "midia_falhou", detalhe: "anexo nao entendido: " + (midia || "").slice(0, 120) }); await flushAlertas(cfg, s10, rep.codvend, instKey, rep.rep, "[midia]"); return j({ ok: true, skip: "midia nao entendida", audio, imagem, rep: rep.rep }); }
    if (/(\bia\b|rob[oo]|\bbot\b|intelig[e]ncia artificial|e a \w+ ou|ou a? ?ia|automatic|gravacao)/.test(norm(texto))) alertas.push({ tipo: "cliente_desconfiou", detalhe: "contato insinuou se e IA/robo" });
    const ctx = { codvend: Number(rep.codvend), rep: rep.rep, contact_id };
    let conv: any = null; { const { data } = await sb.from("agente_conversa").select("*").or(`contact_id.eq.${contact_id || "__none__"},fone.eq.${s10}`).eq("instancia", instKey).order("id", { ascending: false }).limit(1).maybeSingle(); conv = data; }
    const hist: any[] = (conv?.historico || []) as any[]; const ultimoUser = [...hist].reverse().find((m: any) => m.role === "user"); if (ultimoUser && typeof ultimoUser.content === "string" && norm(ultimoUser.content) === norm(texto)) return j({ ok: true, skip: "dedupe", rep: rep.rep });
    const dss = dossieDoPayload(b);
    const memoria = await memoria360(sb, contact_id, parseInt(dss.codparc || "") || null);
    let tema = detectarTema(texto); if (ehRep && tema === "vendas") tema = "representante";
    let playbook = ""; if (nivel >= 2) { const { data: skillRows } = await sb.from("copiloto_skills").select("nome,conteudo").eq("ativo", true); const ordem = (n: string) => n === tema ? 0 : n === "campanhas" ? 1 : 2; playbook = (skillRows || []).sort((a: any, b: any) => ordem(a.nome) - ordem(b.nome)).map((r: any) => "[" + String(r.nome).toUpperCase() + "]\n" + r.conteudo).join("\n\n"); }
    const catt = await catalogoTxt(sb, cfg); const licoes = await licoesTxt(sb);
    const messages: any[] = [...hist.slice(-10), { role: "user", content: texto }];
    const sysBase = aRow ? SYS_PESSOA(personaNome as string) : SYS_NEUTRO();
    let bloco = "";
    if (ehRep) bloco = `\n\nIDENTIDADE (critico): VOCE e ${personaNome ? "a " + personaNome : "o time comercial"}, assistente fixa da Nitron deste representante — sua identidade NAO muda no meio da conversa. Voce fala com ${rep.rep}, um REPRESENTANTE da Nitron (colega, NAO cliente). O nome DELE e ${prim(rep.rep)} — NUNCA o chame pelo seu proprio nome. APOIE-O com a carteira dele.\nPEDIDOS A FATURAR / A LIBERAR / PENDENTES / FATURADOS DO MES: use SEMPRE a ferramenta pedidos_pendentes (nunca consultar_sankhya, nunca escreva SQL de pedido, nunca invente). Ela ja vem filtrada na carteira DELE e recente — nessa visao NAO existe pedido de anos atras nem cliente de outro rep. Explique ONDE esta a pendencia de cada bloco (a_faturar=aguardando a nota; a_liberar=aguardando aprovacao interna; em_elaboracao=ainda montando) e some os totais. Se um bloco vier 0, diga que esta zerado — nao force dado.\nINTELIGENCIAS FUNCIONAIS (ferramentas prontas, use-as em vez de escrever SQL): preco_produto (preco da TABELA daquele cliente — voce ja sabe qual tabela aplica a cada um), credito_cliente (limite/bloqueio/vencido/pode comprar), estoque_produto (disponibilidade antes de prometer), entrega_cliente (status e agendamento). Outras consultas: minha_carteira p/ a lista; buscar_cliente/pedido_cliente/boleto_cliente/saldos_cliente/cobranca_cliente por cliente; consultar_sankhya so p/ o que as ferramentas nao cobrem (sempre filtrando CODVEND=${rep.codvend} e datas recentes). O rep NAO acessa o Sankhya: responda em NOME de cliente + valor + data, nunca codigo cru (a nao ser que ele peca o codigo). Acao que precisa gravar no sistema -> abrir_tarefa e passe o protocolo. NUNCA venda PARA ele nem pergunte o ramo dele.`;
    else { const quem = [dss.nome && ("nome: " + dss.nome), dss.empresa && ("empresa: " + dss.empresa), dss.ramo && ("ramo: " + dss.ramo)].filter(Boolean).join(", "); bloco = `\n\nVoce fala com este CLIENTE${quem ? " (" + quem + ")" : ""}${dss.codparc ? " [cadastro vinculado: codparc " + dss.codparc + "]" : " [SEM cadastro vinculado — p/ dados financeiros/boleto, peca o CNPJ e confirme antes]"}. Voce JA o conhece — NAO pergunte ramo/canal; direcione pela linha campea do ramo e conduza a venda. Se ele perguntar de PEDIDO, NOTA, ENTREGA, BOLETO/2a via ou SALDO dele, confirme AO VIVO no Sankhya (pedido_cliente/boleto_cliente/cobranca_cliente/saldos_cliente com o codparc). Se nao houver codparc vinculado, peca o CNPJ, identifique com buscar_cliente (ao vivo) e so entao passe dado financeiro. Disponibilidade de produto -> estoque_produto (nao prometa sem estoque). Antes de encaminhar um fechamento, cheque credito_cliente (nao venda a quem tem vencido). PRECO de produto: NAO cite ao cliente final; direcione ao vendedor. Nunca responda status de cabeca — sempre do sistema.`; }
    const nivelInstr = nivel >= 4 ? "\n\nMODO PLENO (nivel 4): conduza e RESOLVA de ponta a ponta usando as ferramentas. Nao se limite a informar." : nivel === 3 ? "\n\nMODO PROATIVO: alem de responder, antecipe o proximo passo util." : "";
    const hojeTxt = "\n\nHOJE e " + hojeBRT() + " (data atual REAL; o Sankhya opera nesta data). Datas de 2025 e 2026 sao NORMAIS e ATUAIS — NUNCA trate uma data de 2026 como futura, invalida ou 'erro no sistema'.";
    const sysFull = sysBase + hojeTxt + (nivel < 2 ? SYS_INFORMATIVO : (playbook ? "\n\nMANUAIS DE NEGOCIO DA NITRON (todas as skills — aplique a que o caso pedir; o [" + String(tema).toUpperCase() + "] e o foco agora):\n" + playbook : "")) + nivelInstr + (dss.txt ? "\n\n" + dss.txt : "") + (catt ? "\n\n" + catt : "") + (memoria ? "\n\n" + memoria : "") + bloco + licoes;
    let reply = ""; let houveFalhaBusca = false; let houveRestrito = false; let usouFerramenta = false;
    for (let i = 0; i < 6; i++) {
      const resp = await anthropic(sysFull, messages, true); const blocks = resp.content || []; messages.push({ role: "assistant", content: blocks });
      const toolUses = blocks.filter((x: any) => x.type === "tool_use");
      if (resp.stop_reason !== "tool_use" || !toolUses.length) { reply = blocks.filter((x: any) => x.type === "text").map((x: any) => x.text).join("\n").trim(); break; }
      const results: any[] = [];
      for (const tu of toolUses) { usouFerramenta = true; const out = await runTool(sb, ctx, tu.name, tu.input); if (out && out.restrito) { houveRestrito = true; alertas.push({ tipo: "acesso_restrito", detalhe: "tentou consultar dado restrito: " + JSON.stringify(tu.input).slice(0, 140) }); } else if (out && (out.encontrados === 0 || out.erro)) { houveFalhaBusca = true; alertas.push({ tipo: "lookup_falhou", detalhe: tu.name + " " + JSON.stringify(tu.input).slice(0, 100) + " -> " + (out.aviso || out.erro || "0") }); } results.push({ type: "tool_result", tool_use_id: tu.id, content: JSON.stringify(out).slice(0, 12000) }); }
      messages.push({ role: "user", content: results });
    }
    if (!reply) reply = `Deixa eu confirmar isso no sistema e ja te retorno, ta?`;
    const evasivo = /(vou (verificar|confirmar|checar|ver com|levantar|dar uma olhada|olhar)|deixa eu (ver|confirmar|checar|olhar)|ja (te )?retorno|assim que (eu )?(tiver|souber|confirmar)|preciso (confirmar|verificar|checar))/.test(norm(reply));
    if (evasivo && !houveFalhaBusca && !houveRestrito) alertas.push({ tipo: "esquiva", detalhe: "resposta evasiva" + (usouFerramenta ? "" : " (sem usar ferramenta)") + ": " + reply.slice(0, 150) });
    let enviado = false; let envio: any = null; if (!dry && (contact_id || fone)) { envio = await enviarWhatsapp(contact_id, fone, reply, instancia); enviado = !!envio?.ok; }
    let baseHist = hist; if (conv?.id) { try { const { data: fresh } = await sb.from("agente_conversa").select("historico").eq("id", conv.id).maybeSingle(); if (Array.isArray(fresh?.historico)) baseHist = fresh.historico; } catch (_e) { /* */ } }
    const novoHist = [...baseHist, { role: "user", content: texto }, { role: "assistant", content: reply }].slice(-20);
    const rowState: any = { canal: "whatsapp", contact_id, fone: s10, codvend: ctx.codvend, papel: "rep", estado: "ATIVA", instancia: instKey, historico: novoHist, atualizada_em: new Date().toISOString() };
    let persist_erro: string | null = null;
    if (conv?.id) { const { error } = await sb.from("agente_conversa").update(rowState).eq("id", conv.id); if (error) persist_erro = error.message; } else { rowState.aberta_em = new Date().toISOString(); const { error } = await sb.from("agente_conversa").insert(rowState); if (error) persist_erro = error.message; }
    await flushAlertas(cfg, s10, ctx.codvend, instKey, rep.rep, texto, reply);
    return j({ ok: true, assistente: personaNome, persona, modo_rep: ehRep, auto_atendimento: ehAuto, nivel, inst_key: instKey, audio, imagem, dossie: !!dss.txt, memoria: !!memoria, tema, playbook: !!playbook, licoes: !!licoes, usou_ferramenta: usouFerramenta, restrito: houveRestrito, alertas: alertas.map((a) => a.tipo), busca_falhou: houveFalhaBusca, esquiva: evasivo, modo: modo || "imediato", rep: rep.rep, codvend: ctx.codvend, piloto: fromPilot, dry, texto_recebido: texto, instancia_usada: instancia || null, enviado, reply, persist_erro: persist_erro || undefined });
  } catch (e) { return j({ ok: false, erro: String(e) }, 500); }
});
