-- Lead do anuncio META -> Zaptos da Nina -> qualificacao -> comercial fecha.
--
-- Antes disto o lead do anuncio nao tinha caminho: chegava na instancia da Nina, o
-- copiloto-conversa nao achava rep nem cadastro e devolvia "escalonar" sem responder nada. O
-- primeiro lead (10/09, 00:10 BRT) ficou 12 horas sem resposta.
--
-- Tres coisas faltavam, e todas moram no banco (nao em constante no codigo):
--   1. a Nina nao existia como instancia -> o campanhas-enviar RECUSA instancia fora do
--      cadastro instancia_ghl, entao nenhuma resposta dela sairia;
--   2. nao havia onde anotar o que se apura do lead;
--   3. nao havia playbook: as skills existentes falam com representante e com cliente com
--      cadastro, ninguem falava com quem acabou de clicar num anuncio.
-- Quem usa tudo isto e a funcao copiloto-lead.

-- ---------------------------------------------------------------- 1) a Nina como instancia
-- escopo 'lead' de proposito: 'cliente' faria o campanha-dono e o painel elegerem a Nina como
-- a instancia das campanhas ao cliente, e 'rep' a jogaria no rodizio de assistente de
-- representante (cache-refresh). Ninguem seleciona 'lead' — so o campanhas-enviar, que confere
-- apenas se a instancia esta no cadastro e ativa.
insert into instancia_ghl (instancia, usuario_ghl, usuario_ghl_id, escopo, ativa, empresa, observacao)
values ('Nina', 'Nina Nitron', 'zEMc7K35JO8eUGghqHMN', 'lead', true, 'nitron',
        'Instancia dos leads do anuncio META. escopo lead p/ nao ser eleita por campanha de cliente nem pelo rodizio de rep.')
on conflict (instancia) do update
  set usuario_ghl = excluded.usuario_ghl, usuario_ghl_id = excluded.usuario_ghl_id,
      escopo = excluded.escopo, ativa = true, empresa = excluded.empresa,
      observacao = excluded.observacao, atualizado = now();

-- persona: sem esta linha o prompt cai no SYS_NEUTRO ("o time comercial", sem nome) e ela nao
-- se apresenta como Nina.
insert into assistente_instancia (nome, instancia, ativo)
values ('Nina', 'Nina', true)
on conflict (nome) do update set instancia = excluded.instancia, ativo = true, atualizado = now();

-- ---------------------------------------------------------------- 2) onde o lead e anotado
create table if not exists copiloto_lead (
  id            bigint generated by default as identity primary key,
  criado        timestamptz not null default now(),
  atualizado    timestamptz not null default now(),
  contact_id    text,
  fone          text,
  instancia     text,
  nome          text,
  empresa       text,
  cnpj          text,
  cidade        text,
  uf            text,
  tipo_loja     text,
  ja_revende    text,
  interesse     text,
  sabe_minimo   boolean not null default false,
  temperatura   text,
  resumo        text,
  motivo        text,
  codparc       integer,
  tarefa_id     bigint,
  status        text not null default 'qualificando',
  -- trava de resposta dupla: o envio leva ~20s p/ aparecer na conversa do GHL, e a rodada seguinte
  -- veria a mesma mensagem do lead ainda como "sem resposta".
  ultima_msg_id       text,
  ultima_resposta_em  timestamptz
);
comment on table copiloto_lead is 'Lead do anuncio META atendido pela Nina no Zaptos. status: qualificando -> qualificado -> passado (tarefa aberta p/ o comercial) | descartado (nao e revenda).';
create unique index if not exists copiloto_lead_contact_uk on copiloto_lead (contact_id) where contact_id is not null;
create index if not exists copiloto_lead_fone_ix on copiloto_lead (fone);
create index if not exists copiloto_lead_status_ix on copiloto_lead (status);

-- ---------------------------------------------------------------- 3) parametros e playbook
-- lead_ativo nasce 'nao' de proposito: publicar a funcao nao faz a Nina falar com ninguem, ela
-- so monta o rascunho. Quem liga e o gestor, depois de ver as previas (copiloto-lead?dry=1).
-- lead_espera_min: minutos que a conversa espera antes de a Nina pegar — se um humano responder
-- nesse meio tempo, a conversa sai da lista sozinha (a busca do GHL so traz inbound sem resposta).
insert into copiloto_config (chave, valor) values
  ('lead_ativo',      'nao'),
  ('lead_inst',       'Nina'),
  ('pedido_minimo',   '2500'),
  ('lead_espera_min', '2'),
  ('lead_ate_horas',  '48'),
  -- canal nativo do GHL (WhatsApp oficial da Meta) e a janela de 24h dela: passadas ~24h da
  -- mensagem do lead, texto livre e recusado e so template aprovado passa.
  ('lead_nativo',     'sim'),
  ('lead_janela_h',   '23.5')
on conflict (chave) do nothing;

insert into copiloto_skills (nome, conteudo, ativo) values ('lead',
'LEAD DO ANUNCIO (META): quem chega aqui clicou no anuncio da Nitron e caiu no seu WhatsApp. A primeira mensagem dele quase sempre e generica ("Ola! Posso ter mais informacoes sobre isso?") — nao trate como pergunta vaga: ele viu um anuncio especifico e voce sabe qual.
O ANUNCIO: video curto e comico. Um lojista de camisa florida tenta descansar na praia bebendo agua de coco, o celular toca com "Loja" na tela, e no corte seguinte ele esta no meio do estoque, de bermuda e coco na mao. A fala fecha assim: "lojista, voce nao precisa fazer tudo sozinho. A Nitron ajuda voce a abastecer a sua loja". A dor e sobrecarga: a loja nao deixa ele sair, e abastecer da trabalho. Sua abertura CONTINUA essa conversa (pode citar o video sem contar a piada de novo) e vai direto ao que interessa: que tipo de loja ele tem e o que ele precisa abastecer.
SEU PAPEL e qualificar e aquecer. Quem fecha e o comercial. Voce prepara o terreno e passa com passar_comercial.
O QUE O COMERCIAL PRECISA (levante nesta ordem de importancia, sem interrogatorio): loja (nome/razao) e tipo (bazar, utilidades, variedades, presentes, supermercado, mercearia, magazine, material de construcao); cidade/UF (define o representante da praca); o que ele quer abastecer; se ja compra direto de fabrica ou so de distribuidor; e o CNPJ. Anote cada dado com salvar_lead assim que aparecer.
COMO SONDAR: UMA pergunta por mensagem, duas no maximo, sempre junto de algo util — nunca uma bateria de perguntas. Leia o historico e NUNCA repita pergunta ja respondida. Se ele responder curto, siga em frente com o que tem; se ele desviar, atenda o desvio e volte depois. Nao encha de emoji, nao mande textao, nao repita a mesma frase de outro jeito.
CNPJ: peca depois de gerar valor (nunca na primeira mensagem), e explique por que — "e pra ver se voce ja tem cadastro e quem e o consultor da sua regiao". Com o CNPJ na mao, confira com buscar_cliente: se ele JA tem cadastro, nao trate como lead novo — diga isso e passe pro comercial com passar_comercial.
PEDIDO MINIMO: diga com naturalidade quando a conversa chegar em volume, mix ou como comprar — nunca na abertura. E fato, nao obstaculo: da pra montar um mix bonito com esse valor.
NUNCA diga preco de produto (ele ainda nao tem tabela), prazo de entrega, condicao de pagamento, desconto ou frete: isso e do comercial, e voce diz exatamente isso. Nunca prometa visita nem data.
CATALOGO: mande o link quando ele quiser ver produtos. E link, nao arquivo.
NUNCA use o angulo de concorrencia ("sair na frente", "antes que outro leve") nem pressione com escassez.
QUANDO PASSAR: ja sei a loja, a praca (cidade/UF), o que ele quer, e ele ja sabe do minimo. Chame passar_comercial, e depois diga a ELE o que vai acontecer, sem prometer preco nem prazo: um consultor assume daqui. Se ele responder depois disso, atenda normalmente e nao repita o encaminhamento.
QUANDO DESCARTAR (descartar_lead): consumidor final querendo uma peca, curriculo, fornecedor oferecendo servico, engano de numero. Seja gentil: explique que a Nitron vende pra revenda a partir do pedido minimo e agradeca. Nao humilhe e nao insista.',
true)
on conflict (nome) do nothing;
